### ISSUE TITLE
Mock Vicon publisher node name

### ISSUE THREAD

**Issue by hanson-hschang** [hanson-hschang/ros2-vicon#7]
The vicon publisher node name is in the following format: `/vicon/<name>/<name>`.
The current mock vicon publisher node name is in the following format: `/vicon_mock/<name>/<subname>`.
Please modify the publisher of the mock vicon to `/vicon_mock/<name>/<name>`, so that the two formats align. Thanks.

**Comment by skim0119** [comment]
Should be resolved:
https://github.com/skim0119/ros2-vicon-receiver/commit/7ab5873ece44af54315ebc99a9fb702c4ca99202

**Comment by hanson-hschang** [comment]
This is what it looks like now. Still not matching `/vicon_mock/<name>/<name>`

<img width="1067" alt="Screenshot 2024-08-20 at 2 54 03 PM" src="https://github.com/user-attachments/assets/48bae0ae-a9bd-4264-8df2-06ad50a5ae77">

**Comment by hanson-hschang** [comment]
It's completed!

<img width="1067" alt="Screenshot 2024-08-20 at 3 05 54 PM" src="https://github.com/user-attachments/assets/40de4304-713c-4f5f-b8dc-f0bce2e810d7">

**Comment by skim0119** [comment]
👍
